/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.math.BigDecimal;
import java.util.List;
import java.util.Vector;
import javax.swing.JComboBox;
import javax.swing.JMenuItem;
import javax.swing.JOptionPane;
import javax.swing.JPopupMenu;
import javax.swing.event.TableModelEvent;
import javax.swing.event.TableModelListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import modelo.beans.Producto;
import modelo.logic.ProductoLogic;

/**
 *
 * @author victor
 */
public class FRMViewAdmin extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    BigDecimal total = BigDecimal.ZERO;
    public FRMViewAdmin() {
        initComponents();
        NuevaCotizacion.setVisible(false);
        ListarCotizacion.setVisible(false);
        ListarProductos.setVisible(false);
        IngresarProducto.setVisible(false);
        

        // Agregar el JComboBox al JPanel
        //add(jCB_tipo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        NuevaCotizacion = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jBtn_AgregaCompo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jT_busquedaprod = new javax.swing.JTable();
        jScrollPane5 = new javax.swing.JScrollPane();
        jT_cotiza = new javax.swing.JTable();
        jTFbuscanombre = new javax.swing.JTextField();
        jLabel14 = new javax.swing.JLabel();
        JLtotal = new javax.swing.JLabel();
        ListarCotizacion = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jList2 = new javax.swing.JList<>();
        ListarProductos = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jCB_tipo = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCB_marca = new javax.swing.JComboBox<>();
        jScrollPane4 = new javax.swing.JScrollPane();
        jT_productos = new javax.swing.JTable();
        IngresarProducto = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jCB_tiporegistro = new javax.swing.JComboBox<>();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jCB_marcaregistro = new javax.swing.JComboBox<>();
        jLabel10 = new javax.swing.JLabel();
        jTF_nombre = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jTF_precio = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jTF_ganancia = new javax.swing.JTextField();
        jLabel13 = new javax.swing.JLabel();
        jTF_stock = new javax.swing.JTextField();
        registroProducto = new javax.swing.JButton();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu3 = new javax.swing.JMenu();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenu6 = new javax.swing.JMenu();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel2.setText("Nueva Cotizacion");

        jBtn_AgregaCompo.setText("Agregar componente");
        jBtn_AgregaCompo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jBtn_AgregaCompoActionPerformed(evt);
            }
        });

        jLabel4.setText("Nombre");

        jT_busquedaprod.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "MARCA", "PRECIO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane3.setViewportView(jT_busquedaprod);

        jT_cotiza.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "ID", "NOMBRE", "MARCA", "PRECIO"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane5.setViewportView(jT_cotiza);

        jTFbuscanombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jTFbuscanombreKeyReleased(evt);
            }
        });

        jLabel14.setText("Total :");

        javax.swing.GroupLayout NuevaCotizacionLayout = new javax.swing.GroupLayout(NuevaCotizacion);
        NuevaCotizacion.setLayout(NuevaCotizacionLayout);
        NuevaCotizacionLayout.setHorizontalGroup(
            NuevaCotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NuevaCotizacionLayout.createSequentialGroup()
                .addGroup(NuevaCotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NuevaCotizacionLayout.createSequentialGroup()
                        .addGap(31, 31, 31)
                        .addComponent(jLabel2))
                    .addGroup(NuevaCotizacionLayout.createSequentialGroup()
                        .addGap(59, 59, 59)
                        .addGroup(NuevaCotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(NuevaCotizacionLayout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addGap(36, 36, 36)
                                .addComponent(jTFbuscanombre, javax.swing.GroupLayout.PREFERRED_SIZE, 226, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(8, 8, 8))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NuevaCotizacionLayout.createSequentialGroup()
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 642, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jBtn_AgregaCompo))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, NuevaCotizacionLayout.createSequentialGroup()
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(35, 35, 35)
                                .addComponent(jLabel14)
                                .addGap(18, 18, 18)
                                .addComponent(JLtotal)))))
                .addContainerGap(340, Short.MAX_VALUE))
        );
        NuevaCotizacionLayout.setVerticalGroup(
            NuevaCotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(NuevaCotizacionLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(NuevaCotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jTFbuscanombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(NuevaCotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(NuevaCotizacionLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(NuevaCotizacionLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(jBtn_AgregaCompo)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(NuevaCotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(NuevaCotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel14)
                        .addComponent(JLtotal)))
                .addGap(85, 85, 85))
        );

        jLabel3.setText("Listar Cotizaciones");

        jList2.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "Item 1", "Item 2", "Item 3", "Item 4", "Item 5" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        jScrollPane2.setViewportView(jList2);

        javax.swing.GroupLayout ListarCotizacionLayout = new javax.swing.GroupLayout(ListarCotizacion);
        ListarCotizacion.setLayout(ListarCotizacionLayout);
        ListarCotizacionLayout.setHorizontalGroup(
            ListarCotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListarCotizacionLayout.createSequentialGroup()
                .addGroup(ListarCotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ListarCotizacionLayout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(jLabel3))
                    .addGroup(ListarCotizacionLayout.createSequentialGroup()
                        .addGap(88, 88, 88)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 529, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(107, Short.MAX_VALUE))
        );
        ListarCotizacionLayout.setVerticalGroup(
            ListarCotizacionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListarCotizacionLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel3)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 176, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(125, Short.MAX_VALUE))
        );

        jLabel5.setText("Productos");

        jCB_tipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jLabel1.setText("Tipo");

        jLabel6.setText("Marca:");

        jCB_marca.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jT_productos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "ID", "NOMBRE", "MARCA", "PRECIO", "GANANCIA", "STOCK"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, true, true, true
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jT_productos.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jT_productos.addContainerListener(new java.awt.event.ContainerAdapter() {
            public void componentRemoved(java.awt.event.ContainerEvent evt) {
                jT_productosComponentRemoved(evt);
            }
        });
        jScrollPane4.setViewportView(jT_productos);

        javax.swing.GroupLayout ListarProductosLayout = new javax.swing.GroupLayout(ListarProductos);
        ListarProductos.setLayout(ListarProductosLayout);
        ListarProductosLayout.setHorizontalGroup(
            ListarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListarProductosLayout.createSequentialGroup()
                .addGroup(ListarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(ListarProductosLayout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(jLabel5))
                    .addGroup(ListarProductosLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(jLabel1)
                        .addGap(32, 32, 32)
                        .addComponent(jCB_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(47, 47, 47)
                        .addComponent(jLabel6)
                        .addGap(33, 33, 33)
                        .addComponent(jCB_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(ListarProductosLayout.createSequentialGroup()
                        .addGap(23, 23, 23)
                        .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 667, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(34, Short.MAX_VALUE))
        );
        ListarProductosLayout.setVerticalGroup(
            ListarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(ListarProductosLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel5)
                .addGap(19, 19, 19)
                .addGroup(ListarProductosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCB_tipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel6)
                    .addComponent(jCB_marca, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 235, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(48, 48, 48))
        );

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel7.setText("Ingreso de productos");

        jCB_tiporegistro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Accesorio", "Componente", "Perifrico", "Otros" }));

        jLabel8.setText("Tipo");

        jLabel9.setText("Marca:");

        jCB_marcaregistro.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Logitech", "Microsoft", "Intel", "AMD", "NVIDIA", "Corsair", "Kingston", "Seagate", "Western Digital", "Dell", "Samsung" }));

        jLabel10.setText("Nombre");

        jLabel11.setText("precio");

        jLabel12.setText("ganancia");

        jLabel13.setText("stock");

        jTF_stock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTF_stockActionPerformed(evt);
            }
        });

        registroProducto.setText("Registrar Producto");
        registroProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                registroProductoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout IngresarProductoLayout = new javax.swing.GroupLayout(IngresarProducto);
        IngresarProducto.setLayout(IngresarProductoLayout);
        IngresarProductoLayout.setHorizontalGroup(
            IngresarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IngresarProductoLayout.createSequentialGroup()
                .addGroup(IngresarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(IngresarProductoLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel10))
                    .addGroup(IngresarProductoLayout.createSequentialGroup()
                        .addGap(280, 280, 280)
                        .addComponent(jLabel7))
                    .addGroup(IngresarProductoLayout.createSequentialGroup()
                        .addGap(290, 290, 290)
                        .addComponent(registroProducto))
                    .addGroup(IngresarProductoLayout.createSequentialGroup()
                        .addGap(90, 90, 90)
                        .addGroup(IngresarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addGroup(IngresarProductoLayout.createSequentialGroup()
                                .addGroup(IngresarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, IngresarProductoLayout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(46, 46, 46)
                                        .addComponent(jCB_tiporegistro, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(IngresarProductoLayout.createSequentialGroup()
                                        .addGap(70, 70, 70)
                                        .addComponent(jTF_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 142, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(105, 105, 105)
                                .addGroup(IngresarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(IngresarProductoLayout.createSequentialGroup()
                                        .addComponent(jLabel13)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jTF_stock, javax.swing.GroupLayout.PREFERRED_SIZE, 134, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(IngresarProductoLayout.createSequentialGroup()
                                        .addGroup(IngresarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel11)
                                            .addComponent(jLabel12))
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(IngresarProductoLayout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addGap(33, 33, 33)
                                .addComponent(jCB_marcaregistro, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(190, 190, 190)
                                .addGroup(IngresarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jTF_precio, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jTF_ganancia, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addContainerGap(113, Short.MAX_VALUE))
        );
        IngresarProductoLayout.setVerticalGroup(
            IngresarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(IngresarProductoLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel7)
                .addGap(50, 50, 50)
                .addGroup(IngresarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(jTF_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel11)
                    .addComponent(jTF_precio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(50, 50, 50)
                .addGroup(IngresarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(jCB_marcaregistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jTF_ganancia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(IngresarProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jCB_tiporegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8)
                    .addComponent(jLabel13)
                    .addComponent(jTF_stock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(registroProducto)
                .addGap(71, 71, 71))
        );

        jMenu3.setText("Productos");

        jMenuItem3.setText("Listar");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem3ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem3);

        jMenuItem4.setText("Agregar");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem4ActionPerformed(evt);
            }
        });
        jMenu3.add(jMenuItem4);

        jMenuBar2.add(jMenu3);

        jMenu5.setText("Cotización");

        jMenuItem1.setText("Nueva");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem1ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem1);

        jMenuItem2.setText("Listar");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenuItem2ActionPerformed(evt);
            }
        });
        jMenu5.add(jMenuItem2);

        jMenuBar2.add(jMenu5);

        jMenu6.setText("Ventas");
        jMenuBar2.add(jMenu6);

        jMenu1.setText("Usuarios");
        jMenuBar2.add(jMenu1);

        jMenu2.setText("Salir");
        jMenuBar2.add(jMenu2);

        setJMenuBar(jMenuBar2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(NuevaCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 3, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(ListarProductos, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(IngresarProducto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap())
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(16, 16, 16)
                    .addComponent(ListarCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(NuevaCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(ListarProductos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(IngresarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(38, 38, 38)
                    .addComponent(ListarCotizacion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(819, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jMenuItem2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem2ActionPerformed
        // TODO add your handling code here:
        NuevaCotizacion.setVisible(false);
        ListarCotizacion.setVisible(true);
    }//GEN-LAST:event_jMenuItem2ActionPerformed

    private void jMenuItem1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem1ActionPerformed
        // TODO add your handling code here:
        ListarCotizacion.setVisible(false);
        NuevaCotizacion.setVisible(true);
    }//GEN-LAST:event_jMenuItem1ActionPerformed
    boolean flagcb1 = false;
    boolean flagcb2 = false;
    String tipo = "-";
    String marca = "-";
    private void jMenuItem3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem3ActionPerformed
        // TODO add your handling code here:
        DefaultTableModel tbModel = (DefaultTableModel) jT_productos.getModel();

        ListarProductos.setVisible(true);
        IngresarProducto.setVisible(false);
        NuevaCotizacion.setVisible(false);
        ListarCotizacion.setVisible(false);

        //Load a combobox
        jCB_tipo.removeAllItems();
        jCB_tipo.addItem("-");
        List<String> valores = ProductoLogic.listar_tipo();
        for (String valor : valores) {
            jCB_tipo.addItem(valor);
        }

        jCB_marca.removeAllItems();
        jCB_marca.addItem("-");
        List<String> valores2 = ProductoLogic.listar_marca();
        for (String valor : valores2) {
            jCB_marca.addItem(valor);
        }

        //actionlistener
        jCB_tipo.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                tbModel.setRowCount(0);
                // Capturar el evento de selección y ejecutar tu código aquí
                tipo = (String) jCB_tipo.getSelectedItem();
                if (tipo != null) {
                    if (tipo != "-") {
                        if (flagcb2) {
                            System.out.println("Seleccionado " + tipo + marca);
                            ProductoLogic.listar_productos(tbModel, tipo, marca);
                        } else {
                            System.out.println("Seleccionado " + tipo + marca);
                            ProductoLogic.listar_productos(tbModel, tipo, marca);
                        }
                        flagcb1 = true;
                    } else {
                        flagcb1 = false;
                        if (flagcb2) {
                            System.out.println("Seleccionado " + tipo + marca);
                            ProductoLogic.listar_productos(tbModel, tipo, marca);
                        } else {
                            System.out.println("Seleccionado " + tipo + marca);
                            ProductoLogic.listar_productos(tbModel, tipo, marca);
                        }

                    }

                }
            }
        });
        jCB_marca.addActionListener(new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent e) {
                // Capturar el evento de selección y ejecutar tu código aquí
                tbModel.setRowCount(0);
                marca = (String) jCB_marca.getSelectedItem();
                if (marca != null) {
                    if (marca != "-") {
                        if (flagcb1) {
                            System.out.println("Seleccionado " + tipo + marca);
                            ProductoLogic.listar_productos(tbModel, tipo, marca);
                        } else {
                            System.out.println("Seleccionado " + tipo + marca);
                            ProductoLogic.listar_productos(tbModel, tipo, marca);
                        }
                        flagcb2 = true;
                    } else {
                        flagcb2 = false;
                        if (flagcb1) {
                            System.out.println("Seleccionado " + tipo + marca);
                            ProductoLogic.listar_productos(tbModel, tipo, marca);
                        } else {
                            System.out.println("Seleccionado " + tipo + marca);
                            ProductoLogic.listar_productos(tbModel, tipo, marca);
                        }
                    }

                }
            }
        });

        //
        jT_productos.getModel().addTableModelListener(new TableModelListener() {

            @Override
            public void tableChanged(TableModelEvent e) {

                // Capturamos evento de edición
                if (e.getType() == TableModelEvent.UPDATE) {

                    int fila = e.getFirstRow();
                    int columna = e.getColumn();
                    TableModel modelo = (TableModel) e.getSource();

                    String valor = (String) modelo.getValueAt(fila, columna);
                    int idproducto = (int) modelo.getValueAt(fila, 0);

                    // Actualizar BD
                    //actualizarBaseDatos(fila, columna, valor);
                    ProductoLogic.modificar_producto(idproducto, columna, valor);
                    JOptionPane.showMessageDialog(FRMViewAdmin.this, "Actualizado");
                    System.out.print("hola" + idproducto + columna + valor);

                }

            }
        });
        //ELIMINAR

        JPopupMenu popupMenu = new JPopupMenu();
        JMenuItem eliminarMenuItem = new JMenuItem("Eliminar");
        popupMenu.add(eliminarMenuItem);

        jT_productos.setComponentPopupMenu(popupMenu);
        // Listener para capturar eliminar
        eliminarMenuItem.addActionListener(new ActionListener() {

            @Override
            public void actionPerformed(ActionEvent e) {

                // Obtenemos registro seleccionado
                int filaSel = jT_productos.getSelectedRow();

                if (filaSel >= 0) {

                    // ID Producto (primera columna)
                    int idproducto1 = (int) tbModel.getValueAt(filaSel, 0);

                    // Eliminar de BD  
                    ProductoLogic.eliminar_producto(idproducto1);

                    // Actualizar JTable 
                    tbModel.removeRow(filaSel);
                }

            }
        });
    }//GEN-LAST:event_jMenuItem3ActionPerformed

    private void jT_productosComponentRemoved(java.awt.event.ContainerEvent evt) {//GEN-FIRST:event_jT_productosComponentRemoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jT_productosComponentRemoved

    private void registroProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_registroProductoActionPerformed
        // TODO add your handling code here:
        // Validar cajas de texto (no vacíos, tipo string)

        if (!jTF_nombre.getText().trim().isEmpty()
                && !jCB_marcaregistro.getSelectedItem().toString().trim().isEmpty()
                && !jCB_tiporegistro.getSelectedItem().toString().trim().isEmpty()) {
            try {
                Integer.parseInt(jTF_precio.getText());
                Integer.parseInt(jTF_ganancia.getText());
                Integer.parseInt(jTF_stock.getText());

                Producto prodd = new Producto(jTF_nombre.getText(),
                        jCB_marcaregistro.getSelectedItem().toString(),
                        jCB_tiporegistro.getSelectedItem().toString(),
                        Integer.parseInt(jTF_precio.getText()),
                        Integer.parseInt(jTF_ganancia.getText()),
                        Integer.parseInt(jTF_stock.getText()));
                ProductoLogic.ingresar_producto(prodd);
                JOptionPane.showMessageDialog(FRMViewAdmin.this, "Ingreso con exito");
            } catch (NumberFormatException e) {

            }
        }


    }//GEN-LAST:event_registroProductoActionPerformed

    private void jTF_stockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTF_stockActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTF_stockActionPerformed

    private void jMenuItem4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenuItem4ActionPerformed
        // TODO add your handling code here:
        IngresarProducto.setVisible(true);
        NuevaCotizacion.setVisible(false);
        ListarCotizacion.setVisible(false);
        ListarProductos.setVisible(false);
    }//GEN-LAST:event_jMenuItem4ActionPerformed

    private void jTFbuscanombreKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jTFbuscanombreKeyReleased
        // TODO add your handling code here:
        DefaultTableModel tbModel2 = (DefaultTableModel) jT_busquedaprod.getModel();
        System.out.println("cambio");
        ProductoLogic.busqueda_productos(tbModel2, jTFbuscanombre.getText());
        jT_busquedaprod.repaint();
    }//GEN-LAST:event_jTFbuscanombreKeyReleased

    private void jBtn_AgregaCompoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jBtn_AgregaCompoActionPerformed
        // TODO add your handling code here:
        
        DefaultTableModel tbModel = (DefaultTableModel) jT_busquedaprod.getModel();
        DefaultTableModel tbModel2 = (DefaultTableModel) jT_cotiza.getModel();
        // Obtenemos registro seleccionado
        int filaSel = jT_busquedaprod.getSelectedRow();

        if (filaSel >= 0) {

            // Obtenemos los datos de la fila
            Vector<Object> filaData = new Vector<Object>();
            for (int i = 0; i < tbModel.getColumnCount(); i++) {
                filaData.add(tbModel.getValueAt(filaSel, i));
            }

            //pasar la fila seleccionada a jT_cotiza
            tbModel2.addRow(filaData);
            // Sumar precio a total   
            BigDecimal precio = (BigDecimal) tbModel2.getValueAt(tbModel2.getRowCount() - 1, 3);
            total = total.add(precio);
            JLtotal.setText("S/. "+total);
        }

    }//GEN-LAST:event_jBtn_AgregaCompoActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FRMViewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FRMViewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FRMViewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FRMViewAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FRMViewAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel IngresarProducto;
    private javax.swing.JLabel JLtotal;
    private javax.swing.JPanel ListarCotizacion;
    private javax.swing.JPanel ListarProductos;
    private javax.swing.JPanel NuevaCotizacion;
    private javax.swing.JButton jBtn_AgregaCompo;
    private javax.swing.JComboBox<String> jCB_marca;
    private javax.swing.JComboBox<String> jCB_marcaregistro;
    private javax.swing.JComboBox<String> jCB_tipo;
    private javax.swing.JComboBox<String> jCB_tiporegistro;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JList<String> jList2;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenu jMenu6;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JTextField jTF_ganancia;
    private javax.swing.JTextField jTF_nombre;
    private javax.swing.JTextField jTF_precio;
    private javax.swing.JTextField jTF_stock;
    private javax.swing.JTextField jTFbuscanombre;
    private javax.swing.JTable jT_busquedaprod;
    private javax.swing.JTable jT_cotiza;
    private javax.swing.JTable jT_productos;
    private javax.swing.JButton registroProducto;
    // End of variables declaration//GEN-END:variables
}
